const types = {
	SET_SEARCH_KEYWORD: 'SET_SEARCH_KEYWORD',
	FETCH_BOOKS_PENDING: 'FETCH_BOOKS_PENDING',
	FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
	FETCH_BOOKS_FAILED: 'FETCH_BOOKS_FAILED'
}

export default types
