const types = {
	SET_SEARCH_KEYWORD: 'SET_SEARCH_KEYWORD',
	FETCH_PENDING: 'FETCH_PENDING',
	FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
	FETCH_BOOK_SUCCESS: 'FETCH_BOOK_SUCCESS',
	FETCH_FAILED: 'FETCH_FAILED',
	SUBMIT_PENDING: 'SUBMIT_PENDING',
	SUBMIT_REVIEW_SUCCESS: 'SUBMIT_REVIEW_SUCCESS',
	SUBMIT_FAILED: 'SUBMIT_FAILED'
}

export default types
